# Chapter 3.2
# This script consumes the WC84 FST matrices generated by 04_pairwise_fst.R for nMDS.

required_packages <- c("ggplot2", "ggrepel", "vegan")
missing_packages <- required_packages[!vapply(required_packages, requireNamespace,
  logical(1), quietly = TRUE
)]
if (length(missing_packages) > 0) stop("Install required R packages: ", paste(missing_packages, collapse = ", "))

library(ggplot2)
library(ggrepel)
library(vegan)

repo_root <- normalizePath(".")
metadata_file <- file.path(repo_root, "data", "metadata", "population_info.tsv")
fst_file <- file.path(repo_root, "results", "3.2", "genetic_differentiation", "wc84_pairwise_fst.rds")
result_dir <- file.path(repo_root, "results", "3.2", "genetic_differentiation")

metadata <- read.delim(metadata_file, check.names = FALSE)
fst_matrices <- readRDS(fst_file)

set.seed(20230828)
nmds_table <- do.call(rbind, lapply(names(fst_matrices), function(gene) {
  fst <- fst_matrices[[gene]]
  ordination <- metaMDS(as.dist(fst), k = 2, trymax = 1000, trace = 0, autotransform = FALSE)
  coordinates <- as.data.frame(ordination$points)
  coordinates$Population <- rownames(coordinates)
  coordinates$Superpopulation <- metadata$Superpopulation[
    match(coordinates$Population, metadata$Population)
  ]
  coordinates$Gene <- gene
  coordinates
}))

write.table(nmds_table, file.path(result_dir, "nmds_coordinates.tsv"),
            sep = "\t", quote = FALSE, row.names = FALSE)

plot <- ggplot(nmds_table, aes(x = MDS1, y = MDS2, colour = Superpopulation)) +
  geom_point(size = 2.5) +
  geom_text_repel(aes(label = Population), size = 3, max.overlaps = Inf) +
  facet_wrap(~Gene, scales = "free") +
  scale_colour_manual(values = c(AFR = "#7F3C8D", AMR = "#11A579", EAS = "#3969AC",
                                 EUR = "#F2B701", SAS = "#E73F74")) +
  labs(x = "nMDS axis 1", y = "nMDS axis 2", colour = "Superpopulation") +
  theme_bw(base_size = 11) +
  theme(strip.background = element_blank())

ggsave(file.path(result_dir, "nmds_pairwise_fst.svg"), plot, width = 10, height = 8, units = "in")
