# The code performs nMDS on pairwise Fst matrices generated by pairwise_fst.R.
# Load necessary libraries
library(vegan)
library(ggplot2)
library(ggrepel)
library(rcartocolor)

# Load pairwise Fst matrices
fst_matrices <- readRDS("./pop_diff/wc_pairwise_fst.Rdata")

# Load population info
popdata <- read.delim("20130606_g1k_3202_samples_ped_population.txt", sep=" ")

# Function to perform nMDS based on a pairwise Fst matrix
nmds <- function(fam72_pairwise_fst) {
  # Convert the Fst matrix to a numerical matrix
  nmds_matrix <- as.matrix(fam72_pairwise_fst)
  # Perform nMDS
  fam72_nmds <- metaMDS(nmds_matrix, k = 2, trymax = 10000)
  # Print the nMDS results to console
  print(fam72_nmds)
  return(fam72_nmds)
}

# Function to create a dataframe from nMDS results for plotting
nmds_df <- function(fam72_nmds, popdata) {
  # Convert the nMDS points to a dataframe
  fam72_data <- as.data.frame(fam72_nmds$points)
  fam72_data$Population <- rownames(fam72_data)
  # Add superpopulation and out-of-Africa (OoA) info
  fam72_data$Superpopulation <- popdata$Superpopulation[match(fam72_data$Population, popdata$Population)]
  fam72_data$OoA <- ifelse(fam72_data$Superpopulation == "AFR", "AFR", "OoA")
  return(fam72_data)
}

# Assuming that popdata is already loaded
popdata <- read.delim("20130606_g1k_3202_samples_ped_population.txt", sep=" ")

# Run nMDS analysis for each gene
nmds_results <- lapply(fst_matrices, nmds)

# Names for nMDS results corresponding to each gene
names(nmds_results) <- c("FAM72A", "FAM72B", "FAM72C", "FAM72D")

# Combine all nMDS results into a single dataframe for plotting
df_plot <- do.call(rbind, lapply(names(nmds_results), function(name) {
  df <- nmds_df(nmds_results[[name]], popdata)
  df$Gene <- name
  return(df)
}))

# Create a scatter plot using ggplot2 with text labels and custom color palettes
nmds_plt <- ggplot(data = df_plot, aes(x = MDS1, y = MDS2, color = Superpopulation)) +
  geom_text_repel(max.overlaps = 30, aes(label = Population), size = 3.5) +
  geom_point(size = 2.5) +
  scale_color_manual(values = carto_pal(6, "Bold")[-6]) +
  theme_bw() +
  guides(size = "none", color = guide_legend(ncol = 1, override.aes = list(size = 5))) +
  theme(legend.position = "right", legend.box = "vertical", legend.text = element_text(size = 12), 
        legend.title = element_text(size = 14), axis.title = element_text(size = 12),
        strip.background = element_blank(), strip.placement = "outside", 
        strip.text = element_text(size = 12)) +
  labs(x = "Axis 1", y = "Axis 2", color = "Superpopulation") +
  facet_wrap(~Gene, strip.position = "top")

# Save the plot
svg("./pop_diff/nmds.svg", width = 11.3, height = 10)
print(nmds_plt)
dev.off()
