# The code performs PERMANOVA analysis on pairwise Fst distances for FAM72A-D paralogs generated by pairwise_fst.R. The analysis compared two reduced models: biogeographical ancestry and Out-of-Africa groupings of 26 human populations.
# Load libraries
library(vegan)

# Read pre-computed pairwise Fst matrices and population data
fst_matrices <- readRDS("./pop_diff/wc_pairwise_fst.Rdata")
popdata <- read.delim("20130606_g1k_3202_samples_ped_population.txt", sep=" ")

# Create a data frame that combines population and superpopulation data
fam72_data <- data.frame(Population = popdata$Population, 
                         Superpopulation = popdata$Superpopulation) |> 
  unique()
fam72_data$OoA <- ifelse(fam72_data$Superpopulation == "AFR", "AFR", "OoA")  # Determine Out of Africa status

# Function to run PERMANOVA for each FST matrix
run_permanova <- function(fst_matrix, data) {
  list(
    Superpopulation = adonis2(fst_matrix ~ Superpopulation, data, permutations = 10000),
    OoA = adonis2(fst_matrix ~ OoA, data, permutations = 10000)
  )
}

# Apply PERMANOVA to all FST matrices
permanova_results <- lapply(fst_matrices, run_permanova, data = fam72_data)

# Name the list elements
names(permanova_results) <- c("FAM72A", "FAM72B", "FAM72C", "FAM72D")
